# Stage 0: compile angular frontend
FROM node:current-alpine3.23 AS build
# Set api url
ENV SERVER_API_URL=https://admin-dashboard.abofonsa.com/

RUN npm install -g npm@11.6.2

WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run webapp:prod

# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/target/classes/static/  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
