name: health-connect
services:
  admindashboard:
    image: hc-admin-dashboard:0.0.1
    container_name: hc-admin-dashboard
    hostname: hc-admin-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
      tags:
        - 'hc-admin-dashboard:0.0.1'
        - 'hc-admin-dashboard:latest'
    environment:
      - SERVER_API_URL=http://localhost:5504/
    volumes:
      - './admindashboard:/usr/src/app'
    ports:
      - 127.0.0.1:5506:80
    networks:
      - devnet

networks:
  devnet:
    external: true
    name: devnet
